# Generated by Django 5.0.3 on 2026-09-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student / Participant'), ('host', 'Host / Lecturer / Organizer')], default='student', help_text='Role: student (participant) or host (lecturer/organizer)', max_length=20),
        ),
    ]
